Print Log

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,6 +13,12 @@ jobs:
           working_directory: SwiftUI_Playground/Resources/Firebase
           command: |
             echo "${GOOGLE_SERVICE_INFO_PLIST_BASE64}" | base64 -d > GoogleService-Info.plist
+            if [ $? -eq 0 ]; then
+              echo "GoogleService-Info.plist decoded successfully"
+            else
+              echo "Failed to decode GoogleService-Info.plist" >&2
+              exit 1
+            fi
       - run:
           name: Install Dependencies
           command: bundle install
