CircleCI Danger検証 (#535)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,54 +1,68 @@
 version: 2.1
 
-executors:
-  ios-executor:
-    macos:
-      xcode: "15.3.0" # Select the appropriate Xcode version
-
 jobs:
-  build-and-test:
-    executor: ios-executor
+  build_and_test:
+    macos:
+      xcode: 15.3.0 # Specify the Xcode version
+
     steps:
-      - checkout # Check out the code from the repository
-
-      # Resolve Swift Package Manager dependencies (This will happen automatically with the build)
+      - checkout
       - run:
-          name: Resolve SPM Dependencies
+          name: Setup GoogleService-Info.plist
+          working_directory: SwiftUI_Playground/Resources/Firebase
           command: |
-            xcodebuild -resolvePackageDependencies \
-              -project SwiftUI_Playground.xcodeproj \
-              -scheme SwiftUI_Playground
-
-      # Set up keychain (for code signing if necessary)
+            echo "${GOOGLE_SERVICE_INFO_PLIST_BASE64}" | base64 -d > GoogleService-Info.plist
+            if [ $? -eq 0 ]; then
+              echo "GoogleService-Info.plist decoded successfully"
+            else
+              echo "Failed to decode GoogleService-Info.plist" >&2
+              exit 1
+            fi
       - run:
-          name: Create Keychain
-          command: |
-            security create-keychain -p "" circle.keychain
-            security default-keychain -s circle.keychain
-            security unlock-keychain -p "" circle.keychain
-
-      # Build the app
+          name: Resolve Swift Packages
+          command: xcodebuild -resolvePackageDependencies -scheme "SwiftUI_Playground"
       - run:
-          name: Build the project
-          command: |
-            xcodebuild clean build \
-              -project SwiftUI_Playground.xcodeproj \
-              -scheme SwiftUI_Playground \
-              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
-              CODE_SIGNING_ALLOWED=NO
-
-      # Run tests
+          name: Install Dependencies
+          command: bundle install
       - run:
-          name: Run Unit Tests
+          name: Debug Environment Variables
           command: |
-            xcodebuild test \
-              -project SwiftUI_Playground.xcodeproj \
-              -scheme SwiftUI_Playground \
-              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
+            echo "CI: $CI"
+            echo "CIRCLECI: $CIRCLECI"
+            echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
+            echo "CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME"
+            echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"
+      - run:
+          name: Install SwiftLint
+          command: brew install swiftlint
+      - run:
+          name: Run Danger
+          command: bundle exec danger
+      - run:
+          name: Run Fastlane
+          command: bundle exec fastlane test
+      - run:
+          name: Send Success Notification to Slack
+          when: on_success
+          command: |
+            curl -X POST -H 'Content-type: application/json' \
+            --data '{"channel": "'"$SLACK_DEFAULT_CHANNEL"'", "text": "Build succeeded for project: $CIRCLE_PROJECT_REPONAME in $CIRCLE_PROJECT_USERNAME."}' \
+            https://slack.com/api/chat.postMessage \
+            -H "Authorization: Bearer $SLACK_ACCESS_TOKEN"
+      - run:
+          name: Send Failure Notification to Slack
+          when: on_fail
+          command: |
+            curl -X POST -H 'Content-type: application/json' \
+            --data '{"channel": "'"$SLACK_DEFAULT_CHANNEL"'", "text": "Build failed for project: $CIRCLE_PROJECT_REPONAME in $CIRCLE_PROJECT_USERNAME."}' \
+            https://slack.com/api/chat.postMessage \
+            -H "Authorization: Bearer $SLACK_ACCESS_TOKEN"
 
 workflows:
   version: 2
-  build-and-test:
+  build_and_test:
     jobs:
-      - build-and-test
-
+      - build_and_test:
+          filters:
+            tags:
+              ignore: /.*/ # Ignore tags
